# Copyright (c) 2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Unitree Go2 reinforcement-learning Sim2Sim project (flat and rough terrain)."""

from .isaaclab_cfg import EVAL_TASK_ID, PLAY_TASK_ID, TRAIN_TASK_ID, register_tasks
from .rear_stand_cfg import REAR_STAND_PLAY_TASK_ID, REAR_STAND_TRAIN_TASK_ID
from .rough_cfg import (
    ROUGH_EVAL_TASK_ID,
    ROUGH_EXPERIMENT_NAME,
    ROUGH_PLAY_TASK_ID,
    ROUGH_TRAIN_TASK_ID,
)
from .rough_history_cfg import (
    ROUGH_HISTORY_EVAL_TASK_ID,
    ROUGH_HISTORY_EXPERIMENT_NAME,
    ROUGH_HISTORY_PLAY_TASK_ID,
    ROUGH_HISTORY_TRAIN_TASK_ID,
)
from .yuil_dog_cfg import (
    YUIL_DOG_ROUGH_EVAL_TASK_ID,
    YUIL_DOG_ROUGH_EXPERIMENT_NAME,
    YUIL_DOG_ROUGH_PLAY_TASK_ID,
    YUIL_DOG_ROUGH_TRAIN_TASK_ID,
)
from .yuil_dog_flat_cfg import (
    YUIL_DOG_FLAT_EVAL_TASK_ID,
    YUIL_DOG_FLAT_EXPERIMENT_NAME,
    YUIL_DOG_FLAT_PLAY_TASK_ID,
    YUIL_DOG_FLAT_TRAIN_TASK_ID,
)
from .yuil_dog_flat_low_profile_cfg import (
    YUIL_DOG_FLAT_LOW_PROFILE_EVAL_TASK_ID,
    YUIL_DOG_FLAT_LOW_PROFILE_EXPERIMENT_NAME,
    YUIL_DOG_FLAT_LOW_PROFILE_PLAY_TASK_ID,
    YUIL_DOG_FLAT_LOW_PROFILE_TRAIN_TASK_ID,
)
from .yuil_dog_flat_robotlab_cfg import (
    YUIL_DOG_FLAT_ROBOTLAB_ACTOR_STEP_DIM,
    YUIL_DOG_FLAT_ROBOTLAB_EVAL_TASK_ID,
    YUIL_DOG_FLAT_ROBOTLAB_EXPERIMENT_NAME,
    YUIL_DOG_FLAT_ROBOTLAB_HISTORY_LENGTH,
    YUIL_DOG_FLAT_ROBOTLAB_PLAY_TASK_ID,
    YUIL_DOG_FLAT_ROBOTLAB_RECOVERY_EVAL_TASK_ID,
    YUIL_DOG_FLAT_ROBOTLAB_TRAIN_TASK_ID,
)

__all__ = [
    "EVAL_TASK_ID",
    "PLAY_TASK_ID",
    "REAR_STAND_PLAY_TASK_ID",
    "REAR_STAND_TRAIN_TASK_ID",
    "ROUGH_EVAL_TASK_ID",
    "ROUGH_EXPERIMENT_NAME",
    "ROUGH_HISTORY_EVAL_TASK_ID",
    "ROUGH_HISTORY_EXPERIMENT_NAME",
    "ROUGH_HISTORY_PLAY_TASK_ID",
    "ROUGH_HISTORY_TRAIN_TASK_ID",
    "ROUGH_PLAY_TASK_ID",
    "ROUGH_TRAIN_TASK_ID",
    "TRAIN_TASK_ID",
    "YUIL_DOG_FLAT_EVAL_TASK_ID",
    "YUIL_DOG_FLAT_EXPERIMENT_NAME",
    "YUIL_DOG_FLAT_LOW_PROFILE_EVAL_TASK_ID",
    "YUIL_DOG_FLAT_LOW_PROFILE_EXPERIMENT_NAME",
    "YUIL_DOG_FLAT_LOW_PROFILE_PLAY_TASK_ID",
    "YUIL_DOG_FLAT_LOW_PROFILE_TRAIN_TASK_ID",
    "YUIL_DOG_FLAT_PLAY_TASK_ID",
    "YUIL_DOG_FLAT_ROBOTLAB_ACTOR_STEP_DIM",
    "YUIL_DOG_FLAT_ROBOTLAB_EVAL_TASK_ID",
    "YUIL_DOG_FLAT_ROBOTLAB_EXPERIMENT_NAME",
    "YUIL_DOG_FLAT_ROBOTLAB_HISTORY_LENGTH",
    "YUIL_DOG_FLAT_ROBOTLAB_PLAY_TASK_ID",
    "YUIL_DOG_FLAT_ROBOTLAB_RECOVERY_EVAL_TASK_ID",
    "YUIL_DOG_FLAT_ROBOTLAB_TRAIN_TASK_ID",
    "YUIL_DOG_FLAT_TRAIN_TASK_ID",
    "YUIL_DOG_ROUGH_EVAL_TASK_ID",
    "YUIL_DOG_ROUGH_EXPERIMENT_NAME",
    "YUIL_DOG_ROUGH_PLAY_TASK_ID",
    "YUIL_DOG_ROUGH_TRAIN_TASK_ID",
    "register_tasks",
]
